spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: vaicorinthians
    hikari:
      connection-test-query: SELECT 1

    url: jdbc:mysql://localhost:3306/db_banco?useTimezone=true&serverTimezone=UTC
    username: vinicius
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        hbm2ddl:
          import_files: script/data.sql
    show-sql: true
    hibernate:
      ddl-auto: update
